#FROM dvmarques/openjdk-17-jdk-alpine-with-timezone
#COPY target/demo-0.0.1-SNAPSHOT.jar java-app.jar
#ENTRYPOINT [ "java", "-jar", "java-app.jar" ]


# Etapa de construcción
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa final
FROM dvmarques/openjdk-17-jdk-alpine-with-timezone
WORKDIR /app
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar java-app.jar
ENTRYPOINT ["java", "-jar", "java-app.jar"]